config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index, :show]
  end
  resources :products, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :product_categories
    has_many :products, through: :product_categories
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence: true

    has_many :product_categories
    has_many :categories, through: :product_categories

    has_many :variants, class_name: 'ProductVariant'
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
    belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @category = Category.find(params[:category_id])
        @products = @category.products.includes(:variants).order(:title)
    end

    def show
      @product = Product.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<h1>Categories#index (<%= @categories.length %>)</h1>

<ol>
    <% @categories.each do |category| %>
    <li>
        <%= link_to category_products_path(category) do %>
            <%= category.title %>
            (<%= category.products_count %> products)
        <% end %>
    </li>
    <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h2>
<%= link_to "Categories", root_path %> /
<%= @category.title %> /
Products
</h2>

<ol>
<% @products.each do |product| %>
<li>
  <%= link_to product_path(product) do %>
    <%= product.title %> (<%= number_to_currency product.price %>)

    <ul>
      <% product.variants.each do |variant| %>
        <li>
            <%= variant.title %>
            (<%= number_to_currency variant.price %>)
        </li>
      <% end %>
    </ul>
  <% end %>
</li>
<% end %>
</ol>

app/views/products/show.html.erb
<h2>
  <%= @product.title %>
</h2>
<p>
  <%= @product.description %>
</p>